#!/usr/bin/env python

Import("env")
Import("env_modules")

my_env = env_modules.Clone()

module_obj = []

include_paths = [
    "#../Thirdparty/ffmpeg/Win64/include",
    "D:/gitrepo/MyGodot/Thirdparty/ffmpeg/Win64/include",
    "/usr/local/include",
]
libs = [
    "avcodec",
    "avformat",
    "avutil"
]
libpath = [
    "#../Thirdparty/ffmpeg/Win64/lib",
    "D:/gitrepo/MyGodot/Thirdparty/ffmpeg/Win64/lib",
    "/usr/local/lib"
]

my_env.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

my_env.Prepend(CPPPATH=include_paths, LIBS=libs, LIBPATH=libpath)
env.Prepend(LIBS=libs, LIBPATH=libpath)

# Needed to force rebuilding the module files when the thirdparty library is updated.
# env.Depends(module_obj, thirdparty_obj)
