#!/usr/bin/env python

Import("env")
Import("env_modules")

my_env = env_modules.Clone()

module_obj = []

my_env.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
# env.Depends(module_obj, thirdparty_obj)
